spring.application.name=MainService
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/social-platform

spring.datasource.url= jdbc:postgresql://localhost:5433/social-platform
spring.datasource.username= adm_social_api
spring.datasource.password= social@api
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Nom du suffixe des tables d'audit (ex: menage_aud)
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud
# Permet de stocker le type de modification (0: ADD, 1: MOD, 2: DEL)
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
# Très important : permet à Envers de créer les tables automatiquement si elles n'existent pas
spring.jpa.hibernate.ddl-auto=update